name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages || true
          
          if git show-ref --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
            git reset --hard origin/gh-pages
          else
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Initial gh-pages commit"
          fi

      - name: Create backup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag deploy-$(date '+%Y-%m-%d-%H%M')
          git push origin --tags
          
          zip -r backup-$(date '+%Y%m%d-%H%M%S').zip .
          
          if ! gh release view backup-latest; then
            gh release create backup-latest --title "Latest Backup" --generate-notes
          fi
          
          gh release upload backup-latest backup-*.zip || echo "Upload failed, continuing..."

      - name: Deploy files
        run: |
          git rm -rf . || true

          git checkout main -- index.html
          git checkout main -- CNAME 2>/dev/null || true

          git checkout main -- dist/assets/
          mkdir -p assets
          cp -r dist/assets/* assets/
          rm -rf dist/

          echo "/* /index.html 200" > _redirects

          git add -A
          git commit -m "Deploy: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages --force