name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create gh-pages branch if not exists
        run: |
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Initial empty commit for gh-pages"
            git push origin gh-pages
          fi

      - name: Deploy to gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git merge main --no-ff -m "Merge main into gh-pages"
          git push origin gh-pages