name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create or reset gh-pages branch
        run: |
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git rm -rf .
          else
            git checkout --orphan gh-pages
          fi